[gauntlet]
name = "cswimr's Gauntlet Plugins"
description = """
Collection of Gauntlet plugins by cswimr

Repository: https://www.coastalcommits.com/cswimr/cswimr-gauntlet-plugins
"""

#
# TailwindCSS
#

[[entrypoint]]
id = 'tailwindcss-search-documentation'
name = 'Search TailwindCSS Documentation'
path = 'src/tailwindcss/src/search-documentation.tsx'
icon = 'tailwindcss/entrypoint-icon.png'
type = 'view'
description = """
Search TailwindCSS documentation from Gauntlet!
"""

#
# Miscellaneous
#

[[entrypoint]]
id = 'emojipicker-legacy'
name = 'Emoji Picker'
path = 'src/emojipicker/legacy.tsx'
type = 'inline-view'
description = """
Copy emojis to your clipboard from Gauntlet!
"""

[[entrypoint]]
id = 'emojipicker'
name = 'Emoji Picker'
path = 'src/emojipicker/index.tsx'
type = 'view'
description = """
Copy emojis to your clipboard from Gauntlet!
"""

[[supported_system]]
os = 'linux'

[[supported_system]]
os = 'macos'

[[supported_system]]
os = 'windows'

[permissions]
main_search_bar = ["read"]
clipboard = ["write"]

[permissions.exec]
command = ["xdg-open", "open", "start", "firefox"]
