[gauntlet]
name = 'Emoji Picker'
description = """
Copy emojis to your clipboard from Gauntlet!

Author: cswimr
Repository: https://www.coastalcommits.com/cswimr/gauntlet-emojipicker
"""

[[entrypoint]]
id = 'emojipicker'
name = 'Emoji Picker'
path = 'src/emojipicker.tsx'
type = 'inline-view'
description = """
Copy emojis to your clipboard from Gauntlet!

Author: cswimr
Repository: https://www.coastalcommits.com/cswimr/gauntlet-emojipicker
"""

[permissions]
main_search_bar = ["read"]
clipboard = ["write"]
