[gauntlet]
name = "cswimr's Gauntlet Plugins"
description = """
Collection of Gauntlet plugins by cswimr

Repository: https://www.coastalcommits.com/cswimr/gauntlet-emojipicker
"""

[[entrypoint]]
id = 'emojipicker-legacy'
name = 'Emoji Picker'
path = 'src/emojipicker/legacy.tsx'
type = 'inline-view'
description = """
Copy emojis to your clipboard from Gauntlet!
"""

[[entrypoint]]
id = 'emojipicker'
name = 'Emoji Picker'
path = 'src/emojipicker/index.tsx'
type = 'view'
description = """
Copy emojis to your clipboard from Gauntlet!
"""

[permissions]
main_search_bar = ["read"]
clipboard = ["write"]
