name: Actions

on:
  push:
    branches:
      - main
      - '!gauntlet/release'
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Plugins
    runs-on: docker
    container: www.coastalcommits.com/cswimr/actions:yarn@sha256:3af293679759bde9009ada9849f59b5b8a4c4b085710d6fafa9f88a60d2cd6f5
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build plugins
        run: yarn run build
      - name: Upload build artifact
        uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3
        with:
          name: plugins-build
          path: dist/
