name: Publish Plugins to Release Branch

on: workflow_dispatch

jobs:
  publish:
    name: Publish plugins
    runs-on: docker
    container: www.coastalcommits.com/cswimr/actions:yarn@sha256:a083d5dec41ea9feb1b318aa4868657c4de645750780ad56efd078d9c037ce2e
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Set up SSH key
        uses: actions/ssh-agent@forgejo
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}
          instance-urls: "www.coastalcommits.com"
      - name: Add instance URLs to known_hosts
        run: ssh-keyscan -H www.coastalcommits.com >> ~/.ssh/known_hosts
      - name: Setup Node.js
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4
        with:
          node-version: 18
          cache: 'yarn'
      - name: Configure Git
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@noreply@coastalcommits.com"
          git remote set-url origin git@www.coastalcommits.com:${{ github.repository }}
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Publish plugins to Release branch
        run: yarn run publish
