name: Publish Plugins to Release Branch

on: workflow_dispatch

jobs:
  publish:
    name: Publish plugins
    runs-on: docker
    container: catthehacker/ubuntu:act-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up SSH key
        uses: actions/ssh-agent@forgejo
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}
          instance-urls: "www.coastalcommits.com"
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Configure Git
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@noreply@coastalcommits.com"
          git remote set-url origin git@www.coastalcommits.com:${{ github.repository }}
      - name: Install dependencies
        run: npm ci
      - name: Publish plugins to Release branch
        run: npm run publish
