name: Publish Plugins to Release Branch

on: workflow_dispatch

jobs:
  publish:
    name: Publish plugins
    runs-on: docker
    container: www.coastalcommits.com/cswimr/actions:yarn@sha256:3af293679759bde9009ada9849f59b5b8a4c4b085710d6fafa9f88a60d2cd6f5
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Set up SSH key
        uses: ssh-agent-fork@v9.0.1
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}
          instance-urls: "c.csw.im"
      - name: Add instance URLs to known_hosts
        run: ssh-keyscan -H c.csw.im >> ~/.ssh/known_hosts
      - name: Setup Node.js
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4
        with:
          node-version: 18
          cache: 'yarn'
      - name: Configure Git
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@noreply@c.csw.im"
          git remote set-url origin git@c.csw.im:${{ github.repository }}
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Publish plugins to Release branch
        run: yarn run publish
