// The following file is generated by getting the sitemap: https://tailwindui.com/sitemap.xml
// and converting it to JSON using something like: https://jsonformatter.org/xml-to-json

export default [
  {
    loc: "https://tailwindui.com/",
  },
  {
    loc: "https://tailwindui.com/components",
  },
  {
    loc: "https://tailwindui.com/components/application-ui/data-display/calendars",
  },
  {
    loc: "https://tailwindui.com/components/application-ui/application-shells/stacked",
  },
  {
    loc: "https://tailwindui.com/components/application-ui/application-shells/sidebar",
  },
  {
    loc: "https://tailwindui.com/login",
  },
  {
    loc: "https://tailwindui.com/components/application-ui/lists/tables",
  },
  {
    loc: "https://tailwindui.com/documentation",
  },
  {
    loc: "https://tailwindui.com/components/application-ui/forms/form-layouts",
  },
  {
    loc: "https://tailwindui.com/components/application-ui/forms/input-groups",
  },
  {
    loc: "https://tailwindui.com/all-access",
  },
  {
    loc: "https://tailwindui.com/components/application-ui/headings/page-headings",
  },
  {
    loc: "https://tailwindui.com/templates/catalyst",
  },
  {
    loc: "https://tailwindui.com/components/application-ui/forms/sign-in-forms",
  },
  {
    loc: "https://tailwindui.com/components/application-ui/navigation/pagination",
  },
  {
    loc: "https://tailwindui.com/components/application-ui/navigation/command-palettes",
  },
  {
    loc: "https://tailwindui.com/components/marketing/sections/heroes",
  },
  {
    loc: "https://tailwindui.com/components/",
  },
  {
    loc: "https://tailwindui.com/components/marketing/sections/testimonials",
  },
  {
    loc: "https://tailwindui.com/components/marketing/sections/feature-sections",
  },
  {
    loc: "https://tailwindui.com/components/marketing/sections/newsletter-sections",
  },
  {
    loc: "https://tailwindui.com/components/marketing/sections/team-sections",
  },
  {
    loc: "https://tailwindui.com/templates",
  },
  {
    loc: "https://tailwindui.com/components/marketing/sections/header",
  },
  {
    loc: "https://tailwindui.com/components/marketing/sections/pricing",
  },
  {
    loc: "https://tailwindui.com/components/marketing/sections/content-sections",
  },
  {
    loc: "https://tailwindui.com/components/marketing/sections/logo-clouds",
  },
  {
    loc: "https://tailwindui.com/components/marketing/sections/faq-sections",
  },
  {
    loc: "https://tailwindui.com/components/marketing/sections/footers",
  },
  {
    loc: "https://tailwindui.com/components/marketing/elements/banners",
  },
  {
    loc: "https://tailwindui.com/components/marketing/elements/flyout-menus",
  },
  {
    loc: "https://tailwindui.com/components/application-ui/lists/feeds",
  },
  {
    loc: "https://tailwindui.com/components/application-ui/forms/select-menus",
  },
  {
    loc: "https://tailwindui.com/components/application-ui/forms/radio-groups",
  },
  {
    loc: "https://tailwindui.com/components/application-ui/overlays/dialogs",
  },
  {
    loc: "https://tailwindui.com/components/application-ui/forms/checkboxes",
  },
  {
    loc: "https://tailwindui.com/components/application-ui/elements/dropdowns",
  },
  {
    loc: "https://tailwindui.com/components/ecommerce/components/product-lists",
  },
  {
    loc: "https://tailwindui.com/components/ecommerce/components/category-previews",
  },
  {
    loc: "https://tailwindui.com/components/application-ui/forms/comboboxes",
  },
  {
    loc: "https://tailwindui.com/components/application-ui/elements/buttons",
  },
  {
    loc: "https://tailwindui.com/components/application-ui/navigation/sidebar-navigation",
  },
  {
    loc: "https://tailwindui.com/components/ecommerce/components/product-overviews",
  },
  {
    loc: "https://tailwindui.com/components/application-ui/navigation/navbars",
  },
  {
    loc: "https://tailwindui.com/components/ecommerce/components/shopping-carts",
  },
  {
    loc: "https://tailwindui.com/components/ecommerce/components/product-quickviews",
  },
  {
    loc: "https://tailwindui.com/components/ecommerce/components/promo-sections",
  },
  {
    loc: "https://tailwindui.com/components/ecommerce/components/category-filters",
  },
  {
    loc: "https://tailwindui.com/components/ecommerce/components/product-features",
  },
  {
    loc: "https://tailwindui.com/components/ecommerce/components/reviews",
  },
  {
    loc: "https://tailwindui.com/components/ecommerce/components/order-history",
  },
  {
    loc: "https://tailwindui.com/components/ecommerce/components/store-navigation",
  },
  {
    loc: "https://tailwindui.com/components/ecommerce/components/order-summaries",
  },
  {
    loc: "https://tailwindui.com/components/ecommerce/components/checkout-forms",
  },
  {
    loc: "https://tailwindui.com/templates/spotlight",
  },
  {
    loc: "https://tailwindui.com/components/ecommerce/components/incentives",
  },
  {
    loc: "https://tailwindui.com/templates/salient",
  },
  {
    loc: "https://tailwindui.com/templates/primer",
  },
  {
    loc: "https://tailwindui.com/templates/commit",
  },
  {
    loc: "https://tailwindui.com/templates/protocol",
  },
  {
    loc: "https://tailwindui.com/templates/studio",
  },
  {
    loc: "https://tailwindui.com/preview",
  },
  {
    loc: "https://tailwindui.com/templates/transmit",
  },
  {
    loc: "https://tailwindui.com/templates/pocket",
  },
  {
    loc: "https://tailwindui.com/templates/keynote",
  },
  {
    loc: "https://tailwindui.com/privacy-policy",
  },
  {
    loc: "https://tailwindui.com/templates/syntax",
  },
  {
    loc: "https://tailwindui.com/changelog",
  },
  {
    loc: "https://tailwindui.com/components/marketing/sections/bento-grids",
  },
  {
    loc: "https://tailwindui.com/components/marketing/sections/cta-sections",
  },
  {
    loc: "https://tailwindui.com/components/marketing/sections/stats-sections",
  },
  {
    loc: "https://tailwindui.com/components/marketing/sections/blog-sections",
  },
  {
    loc: "https://tailwindui.com/components/marketing/feedback/404-pages",
  },
  {
    loc: "https://tailwindui.com/components/marketing/sections/contact-sections",
  },
  {
    loc: "https://tailwindui.com/components/marketing/elements/headers",
  },
  {
    loc: "https://tailwindui.com/components/application-ui/headings/card-headings",
  },
  {
    loc: "https://tailwindui.com/components/marketing/page-examples/about-pages",
  },
  {
    loc: "https://tailwindui.com/components/marketing/page-examples/landing-pages",
  },
  {
    loc: "https://tailwindui.com/components/application-ui/data-display/description-lists",
  },
  {
    loc: "https://tailwindui.com/components/application-ui/data-display/stats",
  },
  {
    loc: "https://tailwindui.com/components/marketing/page-examples/pricing-pages",
  },
  {
    loc: "https://tailwindui.com/components/application-ui/application-shells/multi-column",
  },
  {
    loc: "https://tailwindui.com/components/application-ui/headings/section-headings",
  },
  {
    loc: "https://tailwindui.com/components/application-ui/forms/textareas",
  },
  {
    loc: "https://tailwindui.com/components/application-ui/forms/toggles",
  },
  {
    loc: "https://tailwindui.com/components/application-ui/forms/action-panels",
  },
  {
    loc: "https://tailwindui.com/components/application-ui/lists/grid-lists",
  },
  {
    loc: "https://tailwindui.com/components/application-ui/feedback/alerts",
  },
  {
    loc: "https://tailwindui.com/components/application-ui/feedback/empty-states",
  },
  {
    loc: "https://tailwindui.com/components/application-ui/lists/stacked-lists",
  },
  {
    loc: "https://tailwindui.com/components/application-ui/navigation/breadcrumbs",
  },
  {
    loc: "https://tailwindui.com/components/application-ui/navigation/tabs",
  },
  {
    loc: "https://tailwindui.com/components/application-ui/navigation/vertical-navigation",
  },
  {
    loc: "https://tailwindui.com/components/application-ui/overlays/modal-dialogs",
  },
  {
    loc: "https://tailwindui.com/components/application-ui/navigation/progress-bars",
  },
  {
    loc: "https://tailwindui.com/components/application-ui/overlays/notifications",
  },
  {
    loc: "https://tailwindui.com/components/application-ui/overlays/drawers",
  },
  {
    loc: "https://tailwindui.com/components/application-ui/elements/badges",
  },
  {
    loc: "https://tailwindui.com/components/application-ui/elements/avatars",
  },
  {
    loc: "https://tailwindui.com/components/application-ui/layout/containers",
  },
  {
    loc: "https://tailwindui.com/components/application-ui/elements/button-groups",
  },
  {
    loc: "https://tailwindui.com/components/application-ui/layout/media-objects",
  },
  {
    loc: "https://tailwindui.com/components/application-ui/layout/dividers",
  },
  {
    loc: "https://tailwindui.com/components/application-ui/layout/cards",
  },
  {
    loc: "https://tailwindui.com/components/application-ui/page-examples/home-screens",
  },
  {
    loc: "https://tailwindui.com/components/application-ui/layout/list-containers",
  },
  {
    loc: "https://tailwindui.com/components/ecommerce/page-examples/category-pages",
  },
  {
    loc: "https://tailwindui.com/components/application-ui/page-examples/detail-screens",
  },
  {
    loc: "https://tailwindui.com/components/ecommerce/page-examples/order-detail-pages",
  },
  {
    loc: "https://tailwindui.com/components/application-ui/page-examples/settings-screens",
  },
  {
    loc: "https://tailwindui.com/components/ecommerce/page-examples/product-pages",
  },
  {
    loc: "https://tailwindui.com/components/ecommerce/page-examples/shopping-cart-pages",
  },
  {
    loc: "https://tailwindui.com/checkout/1ab56599-ff3e-4666-9686-edda6c81c82a",
  },
  {
    loc: "https://tailwindui.com/checkout/0ed326ca-c1fc-440b-b1ba-bdfb01c43185",
  },
  {
    loc: "https://tailwindui.com/checkout/7b7130a6-68aa-49cb-9f13-818720c60fe8",
  },
  {
    loc: "https://tailwindui.com/password/reset",
  },
  {
    loc: "https://tailwindui.com/components/ecommerce/page-examples/storefront-pages",
  },
  {
    loc: "https://tailwindui.com/license",
  },
  {
    loc: "https://tailwindui.com/checkout/aa651062-caee-4517-b83a-d2aed4cd00cc",
  },
  {
    loc: "https://tailwindui.com/components/ecommerce/page-examples/checkout-pages",
  },
  {
    loc: "https://tailwindui.com/checkout/cc42453b-bfcd-4a7c-8150-37946e36168e",
  },
  {
    loc: "https://tailwindui.com/checkout/237c84cc-13fd-4ca0-b5ac-d5d0a0ea6ac6",
  },
  {
    loc: "https://tailwindui.com/checkout/88b34469-c305-42da-8615-12b24e1cebfa",
  },
  {
    loc: "https://tailwindui.com/checkout/ea20ca6e-20f1-4532-876d-6879d92f5ef1",
  },
  {
    loc: "https://tailwindui.com/components/ecommerce/page-examples/order-history-pages",
  },
  {
    loc: "https://tailwindui.com/checkout/19d4419f-7684-4425-bb49-7dc7c60556d1",
  },
  {
    loc: "https://tailwindui.com/checkout/add9e0e2-e333-4b8c-880e-18b521f76733",
  },
  {
    loc: "https://tailwindui.com/checkout/6ef9edc3-1962-45a4-968a-c307b2cb8001",
  },
  {
    loc: "https://tailwindui.com/templates/radiant",
  },
  {
    loc: "https://tailwindui.com/checkout/d967e538-a015-4ae7-ac59-e61f59857bf5",
  },
  {
    loc: "https://tailwindui.com/checkout/42741d5e-31c7-4d80-9f55-5637a0584db4",
  },
  {
    loc: "https://tailwindui.com/checkout/8a3351de-d4ee-4443-8d80-3c2a8166ff40",
  },
  {
    loc: "https://tailwindui.com/checkout/1b4567e2-5f64-4785-b367-ebad83d11c00",
  },
  {
    loc: "https://tailwindui.com/components/application-ui/navigation/steps",
  },
  {
    loc: "https://tailwindui.com/checkout/b871a18b-d5bc-4aa4-b7fd-051594adedb4",
  },
  {
    loc: "https://tailwindui.com/components/application-ui/layout/panels",
  },
  {
    loc: "https://tailwindui.com/components/application-ui/overlays/slide-overs",
  },
  {
    loc: "https://tailwindui.com/components/application-ui/overlays/modals",
  },
  {
    loc: "https://tailwindui.com/components/marketing/page-examples/about-pages?include=archived",
  },
  {
    loc: "https://tailwindui.com/checkout/461c6bcc-06bd-4c3b-9a15-ae2e4552534c",
  },
  {
    loc: "https://tailwindui.com/components/preview",
  },
];
